### ISSUE TITLE
Quieres un float o un int? 

### ISSUE THREAD

**Issue by a19caorda** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-a19sotean#1]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-a19sotean/blob/36193e078973c97f47d0c9ab7726f9774aaf1fbe/prueba.py#L4

**Comment by a19sotean** [comment]
Un float. Gracias por avisar.

**Comment by a19caorda** [comment]
De nadaaa

**Comment by jaimerabasco** [comment]
Falta asignarte el commit y aplicar labels y milestone @a19sotean 
Cierralo después

**Comment by a19sotean** [comment]
bb771a3bcda989b95b43cf032c881e8f0e685de1

**Comment by jaimerabasco** [comment]
Hay que asignar este issue @a19sotean 
Milestone!

**Comment by a19sotean** [comment]
Listo
