### ISSUE TITLE
No has cerrado la linea correctamente

### ISSUE THREAD

**Issue by sergiovj2001** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-a19sotean#2]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-a19sotean/blob/f4c37d02d6e4661a7153823f52ced6a381ee965f/style.css#L2

al final de esta linea tienes que poner unas ; para que este correctamente cerrada

**Comment by a19sotean** [comment]
Vale, gracias. Ya lo he arreglado
